name: Yolk

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

permissions: read-all

jobs:
  build_python:
    name: "pterodactyl-yolks:python-${{ matrix.tag }}"
    strategy:
      fail-fast: false
      matrix:
        python: [ "3.12" ]

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/endstonemc/pterodactyl-yolks
          tags: type=raw,value=python-${{ matrix.python }}

      - name: Build and Push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: yolks/python
          file: yolks/python/${{ matrix.python }}/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true
